---

#- name: Copy hosts
#  copy:
#    content: |
#      127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
#      ::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
#      {% for host in hostvars %}
#      {% set vars = hostvars[host] %}
#      {{ vars.ansible_host }} {{ host }}
#      {% endfor %}
#    dest: /etc/hosts
#    backup: yes

- name: Copy hosts
  copy:
    content: |
      127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
      ::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
      {% for host in ansible_play_hosts %}
      {% set vars = hostvars[host] %}
      {{ vars.ansible_host }} {{ host }}
      {% endfor %}
    dest: /etc/hosts
    backup: yes

- name: Set hostname
  hostname:
    name: "{{ inventory_hostname }}"
