---

#- name: Set hostname
#  strategy: debug
#  gather_facts: no
#  hosts: hadoop
#  roles:
#    - hostname
#
#- name: ssh-copy-id from Namenode to others
#  hosts: namenode
#  roles:
#    - ssh_copy_id
#
#- name: Stop firewall
#  hosts: hadoop
#  roles:
#    - firewall

#- name: Install Java
#  hosts: hadoop
#  roles:
#    - java

- name: Download and Config Hadoop
  hosts: hadoop
  roles:
    - hadoop_pkg
