---

#- name: Download Hadoop 3.0.0
#  unarchive:
#    src: http://p61og6vza.bkt.clouddn.com/hadoop-3.0.0_isa.tar.gz
#    dest: /opt
#    remote_src: yes
#    creates: "{{ hadoop_src }}"

# Why copy not work, use build local instead
#- name: Download isa-l
#  unarchive:
#    src: http://p61og6vza.bkt.clouddn.com/libisal_2.0.21.tar.gz
#    dest: /usr/lib/
#    remote_src: yes

#- name: Configure HADOOP_HOME
#  copy:
#    content: |
#      export HADOOP_HOME=/opt/hadoop-3.0.0
#      export PATH=${HADOOP_HOME}/bin:$PATH
#    dest: /etc/profile.d/hadoop.sh
#    backup: yes

- name: Config Hadoop etc/hadoop
  copy:
    src: ../templates/etc/hadoop/
    dest: "{{ hadoop_src }}/etc/hadoop/"
    backup: yes

- name: Config Hadoop sbin/start-dfs.sh
  blockinfile:
    insertafter: "^#!"
    block: "{{ lookup('file', '../templates/sbin/start-dfs.sh') }}"
    path: "{{ hadoop_src }}/sbin/start-dfs.sh"
    backup: yes

- name: Config Hadoop sbin/stop-dfs.sh
  blockinfile:
    insertafter: "^#!"
    block: "{{ lookup('file', '../templates/sbin/stop-dfs.sh') }}"
    path: "{{ hadoop_src }}/sbin/stop-dfs.sh"
    backup: yes

- name: Config Hadoop sbin/start-yarn.sh
  blockinfile:
    insertafter: "^#!"
    block: "{{ lookup('file', '../templates/sbin/start-yarn.sh') }}"
    path: "{{ hadoop_src }}/sbin/start-yarn.sh"
    backup: yes

- name: Config Hadoop sbin/stop-yarn.sh
  blockinfile:
    insertafter: "^#!"
    block: "{{ lookup('file', '../templates/sbin/stop-yarn.sh') }}"
    path: "{{ hadoop_src }}/sbin/stop-yarn.sh"
    backup: yes