---

- name: instal expect
  yum:
    name: expect
    state: present

- name: ssh-keygen
  shell: |
    echo -e  'n\n' | ssh-keygen  -f ~/.ssh/id_rsa -t rsa -P ""
    exit 0

- name: delete the remote host key first if exist to deal with remote key changed.
  shell: |
    if [ -f "/$HOME/.ssh/known_hosts" ]; then
        ssh-keygen -f "/$HOME/.ssh/known_hosts" -R "$3"
    fi
  with_items:
    - "{{ groups.hadoop }}"

- name: Push ssh key to remote hosts
  shell: |
    set timeout 10
    spawn ssh-copy-id root@{{ item }}
    expect {
      "(yes/no)?" { send yes\n; exp_continue; }
      "password:" { send 123456\n; exp_continue; }
    }
    exit 0
  args:
    executable: /usr/bin/expect
  with_items:
    - "{{ groups.hadoop }}"

